[package]
name = "ws-contracts"
version = "0.1.0"
edition = "2024"

[dependencies]
hyper-tungstenite = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
rust-extensions = { tag = "0.1.5", git = "https://github.com/MyJetTools/rust-extensions.git" }
